node_js:
  - '4'
env: 
  - NODE_VERSION=4
before_script: 
  - npm install -g mocha
  - npm install
  - node_modules/fluent-ffmpeg/tools/test-travis.sh
script:
  - npm test
sudo: false
addons:
  apt:
    packages:
    - wget
    - tar
    - bzip2
    - flvtool2