matrix:
  include:
    - os: linux
      env: NODE_VERSION=4
    - os: linux
      env: NODE_VERSION=5
before_script: npm install -g mocha
script:
  - node_modules/fluent-ffmpeg/tools/test-travis.sh
  - npm test
sudo: false
addons:
  apt:
    packages:
    - wget
    - tar
    - bzip2
    - flvtool2